command_timeout = 3000

[character]
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜ "

[time]
format = "[$time]($style) "
disabled = false

[gcloud]
disabled = true

[shell]
fish_indicator = "ó°ˆº "
bash_indicator = "î¯Š "
style = "cyan bold"
disabled = false

[aws.region_aliases]
us-east-1 = 'Virgina'
us-west-2 = 'Oregon'

[custom.chezmoi]
detect_files = [".chezmoiroot"]
# This makes the prompt too slow, nice in concept though
# when = "ps aux | grep chezmoi | grep -v grep"
symbol = "ğŸ¥–"
style = "green"
format = "[$symbol]($style)"
