defaults:
  theme: tokyonight-storm

options:
  auto_render_languages:
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: false
  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: false
  # whether to treat a thematic break as a slide end.
  end_slide_shorthand: false

transition:
  # how long the transition should last.
  duration_millis: 800
  # how many frames should be rendered during the transition
  frames: 40
  # the animation to use
  animation:
    style: slide_horizontal

bindings:
  exit: ["<c-c>", "q"]
