defaults:
  preview:
    width: 70
repoPaths:
  maddawik/*: ~/projects/*
  vulncheck/*: ~/work/vulncheck/*
  vulncheck-oss/*: ~/work/vulncheck-oss/*
pager:
  diff: "delta"
keybindings:
  universal:
    - key: ctrl+f
      builtin: pageDown
    - key: ctrl+b
      builtin: pageUp
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
  colors:
    text:
      primary: "#e0def4"
      secondary: "#a9b1d6"
      inverted: "#11111b"
      faint: "#e0def4"
      warning: "#ff9e64"
      error: "#f7768e"
      success: "#4fd6be"
    background:
      selected: "#444a73"
    border:
      primary: "#565f89"
      secondary: "#44415a"
      faint: "#24283b"
